version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    network_mode: host
  redis:
    image: redis
    container_name: redis
    network_mode: host
  workers:
    build:
      context: .
    entrypoint:
      - dramatiq
      - rss.reader.workers.feeds
    image: rss/reader:latest
    container_name: rss_worker
    network_mode: host
    depends_on:
      - mongo
      - redis
  app:
    build:
      context: .
    image: rss/reader:latest
    container_name: rss_reader
    network_mode: host
    depends_on:
      - mongo
      - redis
      - workers
