version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    networks: [rss_reader]
  redis:
    image: redis
    container_name: redis
    networks: [rss_reader]
  api:
    build:
      context: .
      target: builder
    container_name: rss_reader
    networks: [rss_reader]
networks:
  rss_reader:
    name: rss_reader
    driver: host
