FROM python:3.9-slim-bullseye

WORKDIR /app

COPY rss/ ./rss/
COPY requirements.txt ./

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

ENTRYPOINT ["dramatiq"]
CMD ["rss.reader.workers.update_feeds"]
